env:
  es6: true
  node: true
  jest: true
parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - 2
    - never

  arrow-parens: 0
  class-methods-use-this: 0
  comma-dangle:
      - 2
      - only-multiline
  import/first: 0
  import/no-extraneous-dependencies: 0
  import/prefer-default-export: 0
  new-cap: 0
  no-console: 1
  no-debugger: 1
  no-plusplus: 0
  no-restricted-properties: 0
  no-restricted-syntax: 0
  no-undef: 2
  no-use-before-define: 0
  strict: 0
