service: serverless-concourse

# frameworkVersion: "=X.X.X"

plugins:
  - serverless-plugin-typescript
  - serverless-offline-scheduler
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-stack-output
  - serverless-plugin-select
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  profile: konradkiss
  environment: ${file(./serverless/${opt:stage, self:provider.stage}/environment.yml)}
  iamRoleStatements: ${file(./serverless/${opt:stage, self:provider.stage}/iam-role-statements.yml)}
functions: ${file(routes.${opt:stage, self:provider.stage}.yml)}
resources: ${file(./serverless/${opt:stage, self:provider.stage}/resources.yml)}

package:
  individually: true

custom:
  serverless-offline:
    port: 3000
  webpack: ../webpack.${opt:stage, self:provider.stage}.config.js
  output:
    handler: ./serverless/${opt:stage, self:provider.stage}/cf-out.handler
    file: ./.serverless/stack.${opt:stage, self:provider.stage}.json
